package tests;


import com.microsoft.playwright.*;
import com.microsoft.playwright.options.*;
import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;
import java.util.*;
import java.util.regex.Pattern;

public class Example {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
        .setHeadless(false));
      BrowserContext context = browser.newContext();
      Page page = context.newPage();
      page.locator("body").click();
      page.navigate("https://pdsinfosysliveopsdemo2.service-now.com/");
      page.getByLabel("User name").click();
      page.getByLabel("User name").fill("IVS_Testing_User");
      page.getByLabel("User name").press("Tab");
      page.getByLabel("Password", new Page.GetByLabelOptions().setExact(true)).fill("Demo@123");
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Log in")).click();
      page.getByLabel("My ServiceNow landing page").click();
      page.getByLabel("All", new Page.GetByLabelOptions().setExact(true)).click();
      page.getByPlaceholder("Filter").click();
      page.getByLabel("My ServiceNow landing page").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByRole(AriaRole.HEADING, new FrameLocator.GetByRoleOptions().setName("About ServiceNow")).click();
      page.getByLabel("Menu", new Page.GetByLabelOptions().setExact(true)).click();
      page.getByLabel("Scope selectors").click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Update set: Default 1 [Global]")).click();
      page.getByLabel("All", new Page.GetByLabelOptions().setExact(true)).click();
      page.getByLabel("Menu", new Page.GetByLabelOptions().setExact(true)).click();
      page.getByLabel("All", new Page.GetByLabelOptions().setExact(true)).click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("IVS Testing_User: available")).click();
      page.getByRole(AriaRole.MENUITEM, new Page.GetByRoleOptions().setName("Preferences")).click();
      page.getByLabel("Preferences", new Page.GetByLabelOptions().setExact(true)).click();
      page.getByLabel("Primary").getByRole(AriaRole.DOCUMENT).locator("div").filter(new Locator.FilterOptions().setHasText("Display")).click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Close dialog")).click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByRole(AriaRole.HEADING, new FrameLocator.GetByRoleOptions().setName("Using ServiceNow")).click();
      page.getByLabel("All", new Page.GetByLabelOptions().setExact(true)).click();
      page.locator("div").filter(new Locator.FilterOptions().setHasText(Pattern.compile("^ServiceNow$"))).nth(2).click();
      page.locator("span").filter(new Locator.FilterOptions().setHasText(Pattern.compile("^ServiceNow$"))).click();
      assertThat(page.locator("span").filter(new Locator.FilterOptions().setHasText(Pattern.compile("^ServiceNow$")))).isVisible();
      page.locator("button").filter(new Locator.FilterOptions().setHasText("Log in")).click();
      page.getByLabel("User name").click();
      page.getByLabel("User name").fill("IVS_Testing_User");
      page.getByLabel("User name").press("Tab");
      page.getByLabel("Password", new Page.GetByLabelOptions().setExact(true)).fill("Demo@123");
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Log in")).click();
      page.getByRole(AriaRole.HEADING, new Page.GetByRoleOptions().setName("My Team dashboard")).click();
      page.getByLabel("Change dashboard").click();
      page.getByLabel("Refresh dashboard").click();
      page.getByLabel("My ServiceNow landing page").click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("IVS Testing_User: available")).click();
      page.getByRole(AriaRole.MENUITEM, new Page.GetByRoleOptions().setName("Log out")).click();
      page.getByLabel("User name").click();
      page.getByLabel("User name").fill("Invalid_User");
      page.getByLabel("User name").press("Tab");
      page.getByLabel("Password", new Page.GetByLabelOptions().setExact(true)).fill("WrongPasswrod");
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Log in")).click();
      page.navigate("https://pdsinfosysliveopsdemo2.service-now.com/welcome.do");
      assertThat(page.getByText("User name or password invalid", new Page.GetByTextOptions().setExact(true))).isVisible();
      page.getByLabel("User name").click();
      page.getByLabel("User name").fill("IVS_Testing_User");
      page.getByLabel("User name").press("Tab");
      page.getByLabel("Password", new Page.GetByLabelOptions().setExact(true)).fill("Demo@123");
      page.getByLabel("Password", new Page.GetByLabelOptions().setExact(true)).press("Enter");
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Log in")).click();
      page.navigate("https://pdsinfosysliveopsdemo2.service-now.com/now/nav/ui/home");
      assertThat(page.getByText("Welcome to Admin Home, IVS!")).isVisible();
      page.getByLabel("All", new Page.GetByLabelOptions().setExact(true)).click();
      page.getByPlaceholder("Filter").click();
      page.getByPlaceholder("Filter").fill("change");
      page.getByLabel("Create New 1 of").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByText("EmergencySVG/thumbtack-fill-").click();
      page.navigate("https://pdsinfosysliveopsdemo2.service-now.com/now/nav/ui/classic/params/target/change_request.do%3Fsys_id%3D-1%26sysparm_query%3Dchg_model%3D62d10fa1c303101035ae3f52c1d3aec1%5Etype%253Demergency%255EEQ%26sysparm_use_polaris%3Dtrue");
      Page page1 = page.waitForPopup(() -> {
        page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Look up value for field: Configuration item").click();
      });
      page1.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Zoom V.92 USB Modem")).click();
      page1.close();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Short description").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Short description").fill("testing");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Justification").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Justification").fill("test");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Justification").press("CapsLock");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Justification").press("CapsLock");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Justification").press("Tab");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Implementation plan").fill("test");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Implementation plan").press("CapsLock");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Implementation plan").press("CapsLock");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Implementation plan").press("Tab");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Risk and impact analysis").fill("test");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Backout plan").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Backout plan").fill("test");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Test plan").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Test plan").fill("test");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Section Tab Lists").getByText("Schedule").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByRole(AriaRole.BUTTON, new FrameLocator.GetByRoleOptions().setName("Select Planned start date")).click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Saturday, March 8,").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Time: Hour").dblclick();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Time: Hour").fill("18");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Save (Enter)").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByRole(AriaRole.BUTTON, new FrameLocator.GetByRoleOptions().setName("Select Planned end date date")).click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Monday, March 10,").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Save (Enter)").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("additional actions menu").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByRole(AriaRole.MENUITEM, new FrameLocator.GetByRoleOptions().setName("Save")).click();
      page.navigate("https://pdsinfosysliveopsdemo2.service-now.com/now/nav/ui/classic/params/target/change_request.do%3Fsys_id%3D1532198383c8ee10a541e720ceaad309%26sysparm_view%3D%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull");
      assertThat(page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Change Request form section").getByLabel("Type")).hasValue("emergency");
      assertThat(page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Change Request form section").getByLabel("Type")).hasValue("emergency");
      assertThat(page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Change Request form section").getByLabel("Type")).hasValue("emergency");
      assertThat(page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Change Request form section").getByLabel("Type")).hasValue("emergency");
      assertThat(page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Change Request form section").getByLabel("State")).hasValue("-5");
      page.navigate("https://pdsinfosysliveopsdemo2.service-now.com/now/nav/ui/classic/params/target/change_request.do%3Fsys_id%3D1532198383c8ee10a541e720ceaad309%26sysparm_view%3D%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull");
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().locator("#state_model_request_cab_approval").click();
      assertThat(page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByText("The following mandatory")).isVisible();
      assertThat(page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Look up value for field: Assignment group")).isVisible();
      Page page2 = page.waitForPopup(() -> {
        page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Look up value for field: Assignment group").click();
      });
      page2.getByRole(AriaRole.TREEITEM, new Page.GetByRoleOptions().setName("AI-OPS5")).click();
      page2.close();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("additional actions menu").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByRole(AriaRole.MENUITEM, new FrameLocator.GetByRoleOptions().setName("Save")).click();
      assertThat(page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Current stage Authorize 3 of")).isVisible();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().locator("#tabs2_list").getByText("Approvers (6)").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Open record: Bernard").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Back").click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("IVS Testing_User: available")).click();
      page.getByRole(AriaRole.MENUITEM, new Page.GetByRoleOptions().setName("Impersonate user")).click();
      page.getByLabel("Select a user").click();
      page.getByRole(AriaRole.COMBOBOX, new Page.GetByRoleOptions().setName("Select a user")).click();
      page.getByRole(AriaRole.COMBOBOX, new Page.GetByRoleOptions().setName("Select a user")).fill("ber");
      page.locator("[id=\"\\33 7gm9iqm51n1-1904-item-container\"]").getByRole(AriaRole.OPTION, new Locator.GetByRoleOptions().setName("Bernard Laboy Bernard bernard")).click();
      page.getByRole(AriaRole.RADIO, new Page.GetByRoleOptions().setName("Bernard Bernard Bernard")).click();
      page.getByRole(AriaRole.RADIO, new Page.GetByRoleOptions().setName("Bernard Bernard Bernard")).click();
      page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Impersonate user")).click();
      page.getByLabel("All", new Page.GetByLabelOptions().setExact(true)).click();
      page.getByPlaceholder("Filter").click();
      page.getByPlaceholder("Filter").fill("APPROVl");
      page.getByPlaceholder("Filter").press("ArrowRight");
      page.getByPlaceholder("Filter").fill("APPROV");
      page.getByLabel("My Approvals 1 of").click();
      page.locator("iframe[name=\"gsft_main\"]").contentFrame().getByLabel("Requested - Open record: Change Request: CHG0000037").click();
    }
  }
}